apiVersion: apps/v1
kind: Deployment
metadata:
  name: mvc-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mvc-app
  template:
    metadata:
      labels:
        app: mvc-app
    spec:
      containers:
      - name: mvc-app
        image: IMAGE_PLACEHOLDER
        ports:
        - containerPort: 80
