name: Build, Test, and Push Docker Image

on:
  push:
    tags:
      - '*'   # Run on every tag push
  workflow_dispatch:  # Allow manual trigger

jobs:
  build-test-docker:
    runs-on: ubuntu-latest
    env:
      PROJECT_PATH: mvc-default-application
      DOCKER_IMAGE: ${{ secrets.DOCKER_HUB_USERNAME }}/mvc-default-application
      DOTNET_VERSION: '9.0.x'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore dependencies
        run: dotnet restore ${{ env.PROJECT_PATH }}

      - name: Build project
        run: dotnet build ${{ env.PROJECT_PATH }} --configuration Release --no-restore

      - name: Run tests
        run: dotnet test ${{ env.PROJECT_PATH }} --configuration Release --no-build --verbosity normal

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Extract version from tag
        id: vars
        run: echo "TAG_VERSION=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          docker build -t ${{ env.DOCKER_IMAGE }}:${{ env.TAG_VERSION }} -t ${{ env.DOCKER_IMAGE }}:latest -f ${{ env.PROJECT_PATH }}/Dockerfile ./${{ env.PROJECT_PATH }}

      - name: Push Docker images
        run: |
          docker push ${{ env.DOCKER_IMAGE }}:${{ env.TAG_VERSION }}
          docker push ${{ env.DOCKER_IMAGE }}:latest

      # ---- EMAIL NOTIFICATIONS ----
      # - name: Send success email
      #   if: success()
      #   uses: dawidd6/action-send-mail@v3
      #   with:
      #     server_address: ${{ secrets.SMTP_SERVER }}
      #     server_port: ${{ secrets.SMTP_PORT }}
      #     username: ${{ secrets.SMTP_USERNAME }}
      #     password: ${{ secrets.SMTP_PASSWORD }}
      #     subject: "[+] GitHub Actions - Build Success [${{ github.repository }}]"
      #     to: mohammadali.forou@hcltech.com
      #     from: GitHub Actions <noreply@github.com>
      #     body: |
      #       The GitHub Actions workflow for repository **${{ github.repository }}**
      #       completed successfully on ref **${{ github.ref_name }}**.

      # - name: Send failure email
      #   if: failure()
      #   uses: dawidd6/action-send-mail@v3
      #   with:
      #     server_address: ${{ secrets.SMTP_SERVER }}
      #     server_port: ${{ secrets.SMTP_PORT }}
      #     username: ${{ secrets.SMTP_USERNAME }}
      #     password: ${{ secrets.SMTP_PASSWORD }}
      #     subject: "[-] GitHub Actions - Build Failed [${{ github.repository }}]"
      #     to: mohammadali.forou@hcltech.com
      #     from: GitHub Actions <noreply@github.com>
      #     body: |
      #       The GitHub Actions workflow for repository **${{ github.repository }}**
      #       failed on ref **${{ github.ref_name }}**.
      #       Please check the logs: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
