name: Provision Infra

on:
  workflow_dispatch:  # Allow manual trigger

jobs:
  terraform-apply:
    name: Terraform Plan & Apply
    runs-on: ubuntu-latest
    outputs:
      vm_ip: ${{ steps.set_outputs.outputs.vm_ip }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: '1.5.7'

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Terraform Init
        working-directory: terraform
        run: terraform init

      - name: Terraform Plan
        working-directory: terraform
        run: terraform plan -var="ssh_public_key=${{ secrets.SSH_PUBLIC_KEY }}" -var="subscription_id=${{ secrets.AZURE_SUBSCRIPTION_ID }}" -out=tfplan
        continue-on-error: true

      - name: Terraform Apply
        working-directory: terraform
        run: terraform apply -auto-approve -var="ssh_public_key=${{ secrets.SSH_PUBLIC_KEY }}" -var="subscription_id=${{ secrets.AZURE_SUBSCRIPTION_ID }}"

      # Save state for destroy workflow
      - name: Upload Terraform State
        uses: actions/upload-artifact@v4
        with:
          name: terraform-state
          path: |
            ./terraform/.terraform
            ./terraform/.terraform.lock.hcl
            ./terraform/terraform.tfstate